logging:
  file: ${spring.application.name}.log
  level:
     root: INFO
     com:
        scio: DEBUG
server:
   port: 7994
eureka:
  instance:
    hostname: localhost
    metadata-map.cluster: default
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/
#doc: https://www.cnblogs.com/allalongx/p/8383757.html
turbine:
  stream.port: 7994
  aggregator:
    clusterConfig: default
  appConfig: scio-cloud-hystrix
  #clusterNameExpression: new String("default-cluster")
  clusterNameExpression: "'default'"
spring:
   application:
      name: scio-cloud-hystrix
   profiles:
      active: dev
   zipkin:
     base-url: http://localhost:8003
     sender:
       type: web
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
         include: hystrix.stream,health,info,shutdown
#https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/htmlsingle/#production-ready-endpoints-enabling-endpoints
management.endpoints.enabled-by-default: false
management.endpoint.info.enabled: true
management.endpoint.health.enabled: true
management.endpoint.shutdown.enabled: true
management.endpoint.hystrix.stream.enabled: true
#https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/htmlsingle/#production-ready-customizing-management-server-context-path
#http://http://localhost:7994/actuator/hystrix.stream
management.endpoints.web.path-mapping.hystrix.stream: hystrix.stream