version: 2
jobs:
  build:
    docker:
      - image: springcloud/pipeline-base
        user: appuser
    environment:
      _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
      TERM: dumb
    resource_class: large
    steps:
      - checkout
      - run:
          name: build jar
          command: ./gradlew build -x test