logging:
  file: ${spring.application.name}.log
  level:
     root: INFO
     com:
        scio: DEBUG
server:
   port: 7999
spring:
   application:
      name: scio-consul-config
   profiles:
      active: dev