logging:
  file: ${spring.application.name}.log
  level:
     root: INFO
     com:
        scio: DEBUG
server:
   port: 7998
spring:
   application:
      name: scio-eureka-discovery

eureka:
  instance:
    hostname: localhost
    #statusPageUrlPath: /info
    #healthCheckUrlPath: /health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/

#https://docs.spring.io/spring-boot/docs/2.1.2.RELEASE/reference/htmlsingle/#production-ready-endpoints
management:
   endpoints:
      enabled-by-default: false
   endpoint:
      info:
         enabled: true