logging:
  file: ${spring.application.name}.log
  level:
     root: INFO
     com:
        scio: DEBUG
server:
   port: 8004
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/
spring:
   application:
      name: scio-cloud-oauth2-resource
   profiles:
      active: dev
# https://docs.spring.io/spring-security-oauth2-boot/docs/2.1.0.RELEASE/reference/htmlsingle/#boot-features-security-oauth2-resource-server
security:
   oauth2:
      resource:
         userInfoUri: http://localhost:8003/userinfo
         token-info-uri: http://localhost:8003/oauth/check_token
         preferTokenInfo: false
      
#Doc: https://cloud.spring.io/spring-cloud-static/spring-cloud-netflix/2.1.0.RELEASE/single/spring-cloud-netflix.html#netflix-zuul-reverse-proxy
zuul:
  ignoredServices: '*'
  routes:
    scio-eureka-discovery: /scio-eureka-discovery/**
    scio-eureka-discovery-mirror:
      path: /scio-eureka-discovery-mirror/**
      serviceId: scio-eureka-discovery
      stripPrefix: true
    config-server:
      path: /config/**
      url: http://localhost:8000
      stripPrefix: true