logging:
  file: ${spring.application.name}.log
  level:
     root: INFO
     com:
        scio: DEBUG
server:
   port: 7998
spring:
   application:
      name: scio-nacos-client
   profiles:
      active: dev